"""add is debit to account model

Revision ID: 582e65f90ff6
Revises: 10f77cfa319a
Create Date: 2026-03-27 16:31:08.728940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582e65f90ff6'
down_revision: Union[str, Sequence[str], None] = '10f77cfa319a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_debit', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'is_debit')
    # ### end Alembic commands ###
